<a href="https://colab.research.google.com/github/Panchyajanya108/Machine-Learning-Projects/blob/main/Diabetes_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

In [ ]:
#importing the diabetes dataset
data=pd.read_csv('/content/Diabetes.csv')

In [ ]:
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
data.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
#initiating the variables
X=data.drop(['Outcome'], axis=1)
Y=data['Outcome'].values.reshape(-1,1)

Splitting data training and testing dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=60)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train
X_test

array([[-1.12867264,  1.88990175,  0.48216805, ...,  3.48959389,
         5.92010091, -0.6889167 ],
       [ 0.06771062,  0.14360295,  0.08378126, ..., -0.3939078 ,
         2.04984367,  1.02257371],
       [-1.12867264, -0.11040414, -0.11541213, ..., -0.15198475,
         0.07528453, -0.94564026],
       ...,
       [ 0.06771062,  0.96912602,  1.07974824, ..., -0.29204547,
        -0.52830574,  0.25240302],
       [-0.82957683,  0.71511892,  0.78095814, ...,  1.32501917,
         1.84359172, -0.94564026],
       [ 0.06771062, -0.26915858,  0.48216805, ...,  0.9430354 ,
        -0.70422653,  0.42355207]])

Using Logistic Regression

---



In [ ]:
## Training the model with logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
#testing the model 
y_pred = classifier.predict(X_test)

In [ ]:
# Making Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix (Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[90 13]
 [21 30]]


0.7792207792207793

Using KNN CLassifier

In [ ]:
# Training the model using KNN
from sklearn.neighbors import KNeighborsClassifier
KNC = KNeighborsClassifier(n_neighbors=3)
KNC.fit(X_train, Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [ ]:
# Testing the result 
y_pred2 = KNC.predict(X_test) 

In [ ]:
# Making Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix (Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred2)

[[90 13]
 [21 30]]


0.7597402597402597

Using Decision Tree

In [ ]:
# Training the model using Decision Tree
from sklearn.tree import DecisionTreeClassifier
DC = DecisionTreeClassifier()
DC.fit(X_train, Y_train)

DecisionTreeClassifier()

In [ ]:
y_pred3=DC.predict(X_test)

In [ ]:
# Making Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix (Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred3)

[[90 13]
 [21 30]]


0.6948051948051948

Using Support Vector Machine

In [ ]:
# Training the model using Decision Tree
from sklearn.svm import SVC
svcclassifier = SVC(kernel='linear')
svcclassifier.fit(X_train, Y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [ ]:
y_pred4=svcclassifier.predict(X_test)

In [ ]:
# Making Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix (Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred4)

[[90 13]
 [21 30]]


0.7597402597402597

Printing the Results of Accuracy

In [ ]:
print ('Accuracy by Logistic Regression:', accuracy_score(Y_test, y_pred))
print ('Accuracy by KNN:', accuracy_score(Y_test, y_pred2))
print ('Accuracy by Decision Tree:', accuracy_score(Y_test, y_pred3))
print ('Accuracy by SVM:', accuracy_score(Y_test, y_pred4))

Accuracy by Logistic Regression: 0.7792207792207793
Accuracy by KNN: 0.7597402597402597
Accuracy by Decision Tree: 0.6948051948051948
Accuracy by SVM: 0.7597402597402597


In [ ]:
print("Enter the information of as below:")
Pregnancies = int(input("Pregnancies :"))
Glucose = float(input("Glucose:"))
BloodPressure = float(input("BloodPressure:"))
SkinThickness = float(input("SkinThickness:"))
Insulin = float(input("Insulin:"))
BMI = float(input("BMI:"))
DiabetesPedigreeFunction = float(input("DiabetesPedigreeFunction:"))
Age = float(input("Age:"))
output=KNC.predict([[Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
]])
if output ==1:
    print("Patient is suffering from Diabetes")
else:
    print("Patient is not suffering from Diabetes")

Enter the information of as below:
Pregnancies :8
Glucose:152
BloodPressure:82
SkinThickness:32
Insulin:1
BMI:33.24
DiabetesPedigreeFunction:0.525
Age:42
Patient is suffering from Diabetes
